"use client"

import { FormEvent, useState } from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Network, Search, ShieldAlert } from "lucide-react"

type Asset = { name: string; type: string; risk: string; issuer: string; observedAt: string | null }
type Surface = { domain: string; assets: Asset[]; certificates: number; sources: string[]; warning?: string; generatedAt: string }

export function AttackSurfaceWorkbench() {
  const [domain, setDomain] = useState("")
  const [result, setResult] = useState<Surface | null>(null)
  const [loading, setLoading] = useState(false)
  const discover = async (event: FormEvent) => { event.preventDefault(); setLoading(true); try { const response = await fetch(`/api/attack-surface?domain=${encodeURIComponent(domain)}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data) } catch (error) { setResult({ domain, assets: [], certificates: 0, sources: [], generatedAt: new Date().toISOString(), warning: error instanceof Error ? error.message : "Discovery failed" }) } finally { setLoading(false) } }
  return <div className="space-y-5"><Card className="border-primary/20 bg-card/90"><CardContent className="p-5"><form onSubmit={discover} className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input value={domain} onChange={(e) => setDomain(e.target.value)} placeholder="example.com" className="pl-9" /></div><Button disabled={loading || !domain.trim()} className="gap-2"><Network className="h-4 w-4" />{loading ? "Discovering…" : "Map attack surface"}</Button></form><p className="mt-3 text-xs text-muted-foreground">Certificate Transparency is public discovery data. Confirm ownership and authorization before probing any resulting asset.</p></CardContent></Card>{result && <><div className="grid gap-4 sm:grid-cols-3"><Metric label="Discovered assets" value={result.assets.length} /><Metric label="Certificates" value={result.certificates} /><Metric label="High-risk names" value={result.assets.filter((asset) => asset.risk === "high").length} /></div><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><Card className="border-border bg-card/90"><CardHeader><CardTitle>Infrastructure graph</CardTitle></CardHeader><CardContent><div className="relative min-h-72 overflow-hidden rounded border border-primary/20 bg-[radial-gradient(circle_at_50%_50%,rgba(45,212,191,.22),transparent_18%),linear-gradient(135deg,#020303,#0b1513)]"><div className="absolute left-1/2 top-1/2 flex h-24 w-24 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-primary bg-primary/10 text-center text-xs text-primary">{result.domain}</div>{result.assets.slice(0, 12).map((asset, index) => { const angle = index / Math.max(Math.min(result.assets.length, 12), 1) * Math.PI * 2; const left = 50 + Math.cos(angle) * 34; const top = 50 + Math.sin(angle) * 34; return <div key={asset.name} className="absolute -translate-x-1/2 -translate-y-1/2 rounded border border-border bg-card px-2 py-1 text-[10px]" style={{ left: `${left}%`, top: `${top}%` }} title={asset.issuer}>{asset.name}</div> })}</div></CardContent></Card><Card className="border-border bg-card/90"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-orange-300" /> Asset risk register</CardTitle></CardHeader><CardContent className="space-y-2">{result.warning && <p className="rounded border border-yellow-500/30 bg-yellow-500/10 p-3 text-xs text-yellow-100">{result.warning}</p>}{result.assets.map((asset) => <div key={asset.name} className="rounded border border-border/70 p-3"><div className="flex items-center justify-between gap-2"><span className="break-all font-mono text-xs">{asset.name}</span><Badge variant="outline" className={asset.risk === "high" ? "border-red-500/40 text-red-300" : "text-yellow-300"}>{asset.risk}</Badge></div><p className="mt-1 text-[11px] text-muted-foreground">{asset.type} · {asset.issuer}</p></div>)}</CardContent></Card></div></>}</div>
}
function Metric({ label, value }: { label: string; value: number }) { return <Card className="border-border bg-card/90"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono text-2xl text-primary">{value}</p></CardContent></Card> }
