"use client"

import { useMemo, useState } from "react"
import { useLiveThreats } from "@/hooks/use-threats"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { BarChart3, Globe2, Network, ShieldAlert, TrendingUp } from "lucide-react"

export function AnalyticsWorkbench() {
  const { threats, isLoading } = useLiveThreats()
  const [windowDays, setWindowDays] = useState(30)
  const filtered = useMemo(() => { const newest = Math.max(...threats.map((t) => Date.parse(t.timestamp)), Date.now()); return threats.filter((t) => newest - Date.parse(t.timestamp) <= windowDays * 86_400_000) }, [threats, windowDays])
  const daily = useMemo(() => { const result = new Map<string, number>(); filtered.forEach((t) => { const day = t.timestamp.slice(0, 10); result.set(day, (result.get(day) ?? 0) + 1) }); return [...result.entries()].sort() }, [filtered])
  const types = useMemo(() => [...filtered.reduce((map, t) => map.set(t.type, (map.get(t.type) ?? 0) + 1), new Map<string, number>())].sort((a, b) => b[1] - a[1]), [filtered])
  const families = useMemo(() => [...filtered.reduce((map, t) => { const key = t.malwareFamily ?? "Unclassified"; return map.set(key, (map.get(key) ?? 0) + 1) }, new Map<string, number>())].sort((a, b) => b[1] - a[1]).slice(0, 8), [filtered])
  const sources = useMemo(() => [...filtered.reduce((map, t) => map.set(t.source, (map.get(t.source) ?? 0) + 1), new Map<string, number>())].sort((a, b) => b[1] - a[1]), [filtered])
  const maxDay = Math.max(...daily.map(([, count]) => count), 1)
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">{isLoading ? "Loading live analytics…" : `${filtered.length} indicators in the selected window`}</p><div className="flex gap-1">{[7, 30, 90].map((days) => <button key={days} type="button" onClick={() => setWindowDays(days)} className={`rounded border px-3 py-1 text-xs ${windowDays === days ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"}`}>{days}d</button>)}</div></div>
    <div className="grid gap-5 lg:grid-cols-3"><Card className="lg:col-span-2 border-border bg-card/90"><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-teal-300" /> Threat volume trend</CardTitle></CardHeader><CardContent><div className="flex h-48 items-end gap-2 overflow-x-auto border-b border-border/70 pb-2">{daily.length ? daily.map(([day, count]) => <div key={day} className="flex min-w-8 flex-1 flex-col items-center justify-end gap-2"><span className="font-mono text-[10px] text-muted-foreground">{count}</span><div className="w-full rounded-t bg-teal-400/70" style={{ height: `${Math.max(8, count / maxDay * 125)}px` }} title={`${day}: ${count}`} /><span className="text-[9px] text-muted-foreground">{day.slice(5)}</span></div>) : <p className="self-center text-sm text-muted-foreground">No time-series data in this window.</p>}</div></CardContent></Card><Card className="border-border bg-card/90"><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-orange-300" /> Attack vectors</CardTitle></CardHeader><CardContent className="space-y-3">{types.map(([type, count]) => <div key={type}><div className="mb-1 flex justify-between text-xs"><span>{type.toUpperCase()}</span><span className="font-mono text-muted-foreground">{count}</span></div><div className="h-2 rounded bg-muted"><div className="h-2 rounded bg-orange-400" style={{ width: `${count / Math.max(types[0]?.[1] ?? 1, 1) * 100}%` }} /></div></div>)}</CardContent></Card></div>
    <div className="grid gap-5 lg:grid-cols-3"><Card className="border-border bg-card/90"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-red-300" /> Malware prevalence</CardTitle></CardHeader><CardContent className="space-y-2">{families.map(([family, count]) => <div key={family} className="flex items-center justify-between rounded border border-border/60 p-2 text-sm"><span>{family}</span><Badge variant="outline">{count}</Badge></div>)}</CardContent></Card><Card className="border-border bg-card/90"><CardHeader><CardTitle className="flex items-center gap-2"><Network className="h-5 w-5 text-sky-300" /> Provider yield</CardTitle></CardHeader><CardContent className="space-y-2">{sources.map(([source, count]) => <div key={source} className="flex items-center justify-between rounded border border-border/60 p-2 text-sm"><span>{source}</span><span className="font-mono text-primary">{count}</span></div>)}</CardContent></Card><Card className="border-border bg-card/90"><CardHeader><CardTitle className="flex items-center gap-2"><Globe2 className="h-5 w-5 text-emerald-300" /> Geographic density</CardTitle></CardHeader><CardContent><div className="relative h-44 overflow-hidden rounded border border-primary/20 bg-[radial-gradient(circle_at_20%_35%,rgba(45,212,191,.45),transparent_13%),radial-gradient(circle_at_70%_45%,rgba(56,189,248,.35),transparent_16%),radial-gradient(circle_at_50%_75%,rgba(250,204,21,.3),transparent_12%),linear-gradient(135deg,#020303,#0b1513)]"><div className="absolute inset-x-4 top-1/2 border-t border-primary/20" /><div className="absolute inset-y-4 left-1/2 border-l border-primary/20" /></div><p className="mt-2 text-xs text-muted-foreground">Geo enrichment is shown when an upstream provider returns country or coordinates; raw IOC feeds may not include location.</p></CardContent></Card></div>
  </div>
}
